<?php
/**
 * Created by PhpStorm.
 * User: barsa
 * Date: 23-Aug-17
 * Time: 13:03
 */

namespace app\model_extended;


use app\models\VwAllServices;

class SERVICES_COUNT_MODEL extends VwAllServices
{
    public function attributeLabels()
    {
        $labels = parent::attributeLabels(); // TODO: Change the autogenerated stub
        $labels['RESERVATIONS'] = 'Number of Reservations';
        return $labels;
    }

    public static function GetReservationsCount($OFFERED_SERVICE_ID)
    {
        $data = RESERVED_SERVICES::find()->where(['OFFERED_SERVICE_ID' => $OFFERED_SERVICE_ID])->count('OFFERED_SERVICE_ID');
        return $data;
    }
}